[package]
name = "rust-image-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.28"
image = "0.23.14"
imageproc = "0.21.0"
img_hash = "3.2.0"
ordered-float = "4.2.2"
rand = "0.8.5"
rusttype = "0.9.3"
